language: cpp

sudo: required
dist: trusty

os:
    - linux
    # - osx

compiler:
    - gcc
    # - clang

script:
    # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install cmake; fi
    # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd /usr/include/X11/extensions && sudo ln -s XI.h XInput.h && cd -; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];   then CPPFLAGS=-Wno-deprecated-declarations make; fi
    - mkdir build
    - cd build
    - cmake .. && make

addons:
  apt:
    packages:
    - git
    - cmake
    - libosmesa6-dev
    - libegl1-mesa-dev
    - libxi-dev
    - freeglut3-dev
